import { VNode } from "vue";
declare const camelize: (str: any) => any;
declare const parseStyleText: (cssText?: string, camel?: boolean) => {};
declare const hasProp: (instance: any, prop: any) => boolean;
declare const slotHasProp: (slot: any, prop: any) => boolean;
declare const filterProps: (props: any, propsData?: {}) => {};
declare const getSlots: (ele: any) => {};
declare const getSlotOptions: (ele: any) => any;
declare const getOptionProps: (instance: any) => any;
declare const getComponentFromProp: (instance: any, prop: any) => any;
declare const getAllProps: (ele: any) => any;
declare const getPropsData: (ele: any) => any;
declare const getValueByProp: (ele: any, prop: any) => any;
declare const getAttrs: (ele: any) => any;
declare const getKey: (ele: any) => any;
export declare function getEvents(child: any): {};
export declare function getClass(ele: any): {};
export declare function getStyle(ele: any, camel: any): any;
export declare function getComponentName(opts: any): any;
export declare function isEmptyElement(ele: any): boolean;
export declare function filterEmpty(children?: VNode[]): Array<VNode>;
declare const initDefaultProps: (propTypes: any, defaultProps: any) => any;
export declare function mergeProps(): {};
declare function isValidElement(element: any): any;
export { hasProp, filterProps, getOptionProps, getComponentFromProp, getSlotOptions, slotHasProp, getPropsData, getKey, getAttrs, getValueByProp, parseStyleText, initDefaultProps, isValidElement, camelize, getSlots, getAllProps, };
export default hasProp;
